### ISSUE TITLE
Startup problem on libreelec 10.0, generic x64

### ISSUE THREAD

**Issue by beatstick** [veldenb/plugin.program.moonlight-qt#12]
Hi, 
this addon seems to have installed correctly, kodi gives no errors. 
However, trying to start moonlight on libreelec, the OS soft resets and does not start the program.

I checked via ssh, and there is no docker container running anything moonlight related.

**Comment by veldenb** [comment]
It would be helpful if you could run the AppImage-version, it would be easier to diagnose the problem.

**Comment by J-o-h-n-s** [comment]
Same problem, also running generic x64. Runing on old macbook pro.

Tried running with commented lines, doesn't help. Goes to connact screen, then goes straitght back where we were in KODI, instead of relaunching it. Will leave logs under, and try with the AppImg on a "normal" distro now.


`Platform generic detected...
Custom ALSA audio device: 'hdmi:CARD=HDMI,DEV=0'
--- Starting Moonlight ---
00:00:00 - SDL Info (0): Compiled with SDL 2.0.21
00:00:00 - SDL Info (0): Running with SDL 2.0.21
00:00:00 - Qt Info: No translation available for  "C"
00:00:01 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:02 - Qt Info: Found "gamecontrollerdb.txt" at "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:02 - SDL Info (0): Loaded 175 new gamepad mappings
00:00:02 - SDL Info (0): V-sync disabled
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0
00:00:02 - SDL Info (0): Initialized VAAPI 1.11
00:00:02 - SDL Info (0): Driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1)
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x3231564e -> nv12.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x30313050 -> p010le.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x36313050 -> unknown.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x30323449 -> yuv420p.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x32315659 -> yuv420p.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x56595559 -> unknown.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x32595559 -> yuyv422.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x59565955 -> uyvy422.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x41524742 -> bgra.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x41424752 -> rgba.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x58524742 -> bgr0.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Format 0x58424752 -> rgb0.
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] VAAPI driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1).
00:00:02 - FFmpeg: [AVHWDeviceContext @ 0x7f37e006f2c0] Driver not found in known nonstandard list, using standard behaviour.
00:00:02 - SDL Info (0): VAAPI driver supports exporting DRM PRIME surface handles
00:00:02 - SDL Info (0): Using VAAPI accelerated renderer on x11
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Format vaapi_vld chosen by get_format().
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Format vaapi_vld requires hwaccel initialisation.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Considering format 0x3231564e -> nv12.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x1.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Direct mapping disabled: deriving image does not work: 1 (operation failed).
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x2.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x3.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x4.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x5.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x6.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x7.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x8.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x9.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0xa.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0xb.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0xc.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0xd.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0xe.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0xf.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x10.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x11.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x12.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x13.
00:00:02 - FFmpeg: [AVHWFramesContext @ 0x7f37e0431300] Created surface 0x14.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Considering format 0x3231564e -> nv12.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Decode context initialised: 0x15/0x16.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Reinit context to 1280x720, pix_fmt: vaapi_vld
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Param buffer (type 0, 672 bytes) is 0x17.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Param buffer (type 1, 240 bytes) is 0x18.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Slice 0 param buffer (3128 bytes) is 0x19.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Slice 0 data buffer (75 bytes) is 0x1a.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Slice 1 param buffer (3128 bytes) is 0x1b.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Slice 1 data buffer (80 bytes) is 0x1c.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Slice 2 param buffer (3128 bytes) is 0x1d.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Slice 2 data buffer (85 bytes) is 0x1e.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Slice 3 param buffer (3128 bytes) is 0x1f.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Slice 3 data buffer (97 bytes) is 0x20.
00:00:02 - FFmpeg: [h264 @ 0x7f37e039de40] Decode to surface 0x14.
00:00:02 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:03 - Qt Info: Found "gamecontrollerdb.txt" at "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:03 - SDL Info (0): Loaded 175 new gamepad mappings
ioctl (GFEATURE): Input/output error
00:00:08 - Qt Info: Processing new PC at "192.168.10.103:47989" from user with IPv6 address "<NULL>"
00:00:08 - Qt Info: Executing request: "http://192.168.10.103:47989/serverinfo?uniqueid=0123456789ABCDEF&uuid=af5e4c03ca0a4ae6ad404a319a6eabba"
00:00:08 - Qt Debug: Current Moonlight version: "3.2.0"
00:00:08 - Qt Info: Gamepad mappings are up to date
00:00:08 - Qt Info: Executing request: "https://192.168.10.103:47984/serverinfo?uniqueid=0123456789ABCDEF&uuid=baaf50f79e8d46e3abe355c16651b9a1"
00:00:08 - Qt Info: Discovered mDNS host: "DESKTOP-69K9E28.local."
00:00:08 - Qt Info: Latest supported GFE server: "99.99.99.99"
00:00:08 - Qt Info: "DESKTOP-69K9E28" is now at "192.168.10.103:47989"
00:00:08 - Qt Debug: Found update manifest match for current platform
00:00:08 - Qt Debug: Latest version of Moonlight for this platform is: "3.2.0"
00:00:08 - Qt Debug: Update manifest version equal to current version
00:00:08 - Qt Info: Found "ModeSeven.ttf" at ":/data/ModeSeven.ttf"
00:00:08 - Qt Info: "DESKTOP-69K9E28" is now online at "192.168.10.103:47989"
00:00:08 - Qt Info: Resolved "DESKTOP-69K9E28.local." to QHostAddress("192.168.10.103")
00:00:08 - Qt Info: Resolved "DESKTOP-69K9E28.local." to QHostAddress("fe80::1540:fd8a:6afb:1eba")
00:00:08 - Qt Info: Server GPU: "NVIDIA GeForce GTX 960"
00:00:08 - Qt Info: Server GFE version: "3.25.0.84"
00:00:08 - SDL Info (0): Video bitrate: 10000 kbps
00:00:09 - SDL Info (0): Desired audio buffer: 240 samples (960 bytes)
00:00:09 - SDL Info (0): Obtained audio buffer: 240 samples (960 bytes)
00:00:09 - SDL Info (0): Audio channel count: 2
00:00:09 - SDL Info (0): Audio channel mask: 3
00:00:09 - SDL Info (0): V-sync disabled
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0
00:00:09 - SDL Info (0): Initialized VAAPI 1.11
00:00:09 - SDL Info (0): Driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1)
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x3231564e -> nv12.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x30313050 -> p010le.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x36313050 -> unknown.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x30323449 -> yuv420p.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x32315659 -> yuv420p.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x56595559 -> unknown.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x32595559 -> yuyv422.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x59565955 -> uyvy422.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x41524742 -> bgra.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x41424752 -> rgba.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x58524742 -> bgr0.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Format 0x58424752 -> rgb0.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] VAAPI driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1).
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0037180] Driver not found in known nonstandard list, using standard behaviour.
00:00:09 - SDL Info (0): VAAPI driver supports exporting DRM PRIME surface handles
00:00:09 - SDL Info (0): Using VAAPI accelerated renderer on x11
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Decoding VPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Main profile bitstream
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Decoding SPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Main profile bitstream
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Decoding VUI
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Decoding PPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Format vaapi_vld chosen by get_format().
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Format vaapi_vld requires hwaccel initialisation.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] HEVC profile Main is found.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] No support for codec hevc profile 1.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Format vaapi_vld not usable, retrying get_format() without it.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0311300] Error parsing NAL unit #3.
00:00:09 - SDL Warn (0): Test decode failed (avcodec_send_packet): Operation not permitted
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0
00:00:09 - SDL Info (0): Initialized VAAPI 1.11
00:00:09 - SDL Info (0): Driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1)
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x3231564e -> nv12.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x30313050 -> p010le.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x36313050 -> unknown.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x30323449 -> yuv420p.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x32315659 -> yuv420p.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x56595559 -> unknown.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x32595559 -> yuyv422.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x59565955 -> uyvy422.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x41524742 -> bgra.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x41424752 -> rgba.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x58524742 -> bgr0.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Format 0x58424752 -> rgb0.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] VAAPI driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1).
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e03025c0] Driver not found in known nonstandard list, using standard behaviour.
00:00:09 - SDL Info (0): Using direct rendering with VAEntrypointVideoProc
00:00:09 - SDL Info (0): Using VAAPI accelerated renderer on x11
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Decoding VPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Main profile bitstream
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Decoding SPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Main profile bitstream
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Decoding VUI
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Decoding PPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Format vaapi_vld chosen by get_format().
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Format vaapi_vld requires hwaccel initialisation.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] HEVC profile Main is found.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] No support for codec hevc profile 1.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Format vaapi_vld not usable, retrying get_format() without it.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0027f40] Error parsing NAL unit #3.
00:00:09 - SDL Warn (0): Test decode failed (avcodec_send_packet): Operation not permitted
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e019bb00] Successfully created a VDPAU device (G3DVL VDPAU Driver Shared Library version 1.0) on X11 display :0.0
00:00:09 - SDL Info (0): Driver: G3DVL VDPAU Driver Shared Library version 1.0
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e038d000] Successfully created a VDPAU device (G3DVL VDPAU Driver Shared Library version 1.0) on X11 display :0.0
00:00:09 - SDL Info (0): Driver: G3DVL VDPAU Driver Shared Library version 1.0
00:00:09 - SDL Info (0): Using VDPAU accelerated renderer
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Decoding VPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Main profile bitstream
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Decoding SPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Main profile bitstream
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Decoding VUI
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Decoding PPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Format vdpau chosen by get_format().
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Format vdpau requires hwaccel initialisation.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Failed setup for format vdpau: hwaccel initialisation returned error.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Format vdpau not usable, retrying get_format() without it.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0028040] Error parsing NAL unit #3.
00:00:09 - SDL Warn (0): Test decode failed (avcodec_send_packet): Operation not permitted
00:00:09 - SDL Info (0): Using SDL renderer
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] Decoding VPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] Main profile bitstream
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] Decoding SPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] Main profile bitstream
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] Decoding VUI
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] Decoding PPS
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] Format yuv420p chosen by get_format().
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] Output frame with POC 3.
00:00:09 - FFmpeg: [hevc @ 0x7f37e0742b80] Decoded frame with POC 3.
00:00:09 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:09 - SDL Info (0): V-sync disabled
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0
00:00:09 - SDL Info (0): Initialized VAAPI 1.11
00:00:09 - SDL Info (0): Driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1)
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x3231564e -> nv12.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x30313050 -> p010le.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x36313050 -> unknown.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x30323449 -> yuv420p.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x32315659 -> yuv420p.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x56595559 -> unknown.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x32595559 -> yuyv422.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x59565955 -> uyvy422.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x41524742 -> bgra.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x41424752 -> rgba.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x58524742 -> bgr0.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x58424752 -> rgb0.
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] VAAPI driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1).
00:00:09 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Driver not found in known nonstandard list, using standard behaviour.
00:00:09 - SDL Info (0): VAAPI driver supports exporting DRM PRIME surface handles
00:00:09 - SDL Info (0): Using VAAPI accelerated renderer on x11
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Format vaapi_vld chosen by get_format().
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Format vaapi_vld requires hwaccel initialisation.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Considering format 0x3231564e -> nv12.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x1.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Direct mapping disabled: deriving image does not work: 1 (operation failed).
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x2.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x3.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x4.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x5.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x6.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x7.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x8.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x9.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0xa.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0xb.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0xc.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0xd.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0xe.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0xf.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x10.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x11.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x12.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x13.
00:00:09 - FFmpeg: [AVHWFramesContext @ 0x7f37e03282c0] Created surface 0x14.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Considering format 0x3231564e -> nv12.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Decode context initialised: 0x15/0x16.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Reinit context to 1280x720, pix_fmt: vaapi_vld
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Param buffer (type 0, 672 bytes) is 0x17.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Param buffer (type 1, 240 bytes) is 0x18.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Slice 0 param buffer (3128 bytes) is 0x19.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Slice 0 data buffer (75 bytes) is 0x1a.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Slice 1 param buffer (3128 bytes) is 0x1b.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Slice 1 data buffer (80 bytes) is 0x1c.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Slice 2 param buffer (3128 bytes) is 0x1d.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Slice 2 data buffer (85 bytes) is 0x1e.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Slice 3 param buffer (3128 bytes) is 0x1f.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Slice 3 data buffer (97 bytes) is 0x20.
00:00:09 - FFmpeg: [h264 @ 0x7f37e023eac0] Decode to surface 0x14.
00:00:09 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:09 - SDL Info (0): Desired audio buffer: 240 samples (960 bytes)
00:00:09 - SDL Info (0): Obtained audio buffer: 240 samples (960 bytes)
00:00:09 - Qt Info: Found "gamecontrollerdb.txt" at "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:09 - SDL Info (0): Loaded 175 new gamepad mappings
00:00:09 - SDL Info (0): V-sync disabled
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0
00:00:10 - SDL Info (0): Initialized VAAPI 1.11
00:00:10 - SDL Info (0): Driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1)
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x3231564e -> nv12.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x30313050 -> p010le.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x36313050 -> unknown.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x30323449 -> yuv420p.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x32315659 -> yuv420p.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x56595559 -> unknown.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x32595559 -> yuyv422.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x59565955 -> uyvy422.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x41524742 -> bgra.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x41424752 -> rgba.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x58524742 -> bgr0.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Format 0x58424752 -> rgb0.
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] VAAPI driver: Mesa Gallium driver 21.0.3 for AMD TURKS (DRM 2.50.0 / 5.10.76, LLVM 11.0.1).
00:00:10 - FFmpeg: [AVHWDeviceContext @ 0x7f37e0307dc0] Driver not found in known nonstandard list, using standard behaviour.
00:00:10 - SDL Info (0): VAAPI driver supports exporting DRM PRIME surface handles
00:00:10 - SDL Info (0): Using VAAPI accelerated renderer on x11
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Format vaapi_vld chosen by get_format().
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Format vaapi_vld requires hwaccel initialisation.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Considering format 0x3231564e -> nv12.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x1.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Direct mapping disabled: deriving image does not work: 1 (operation failed).
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x2.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x3.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x4.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x5.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x6.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x7.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x8.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x9.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0xa.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0xb.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0xc.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0xd.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0xe.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0xf.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x10.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x11.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x12.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x13.
00:00:10 - FFmpeg: [AVHWFramesContext @ 0x7f37e07466c0] Created surface 0x14.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Considering format 0x3231564e -> nv12.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Decode context initialised: 0x15/0x16.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Reinit context to 1280x720, pix_fmt: vaapi_vld
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Param buffer (type 0, 672 bytes) is 0x17.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Param buffer (type 1, 240 bytes) is 0x18.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Slice 0 param buffer (3128 bytes) is 0x19.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Slice 0 data buffer (75 bytes) is 0x1a.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Slice 1 param buffer (3128 bytes) is 0x1b.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Slice 1 data buffer (80 bytes) is 0x1c.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Slice 2 param buffer (3128 bytes) is 0x1d.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Slice 2 data buffer (85 bytes) is 0x1e.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Slice 3 param buffer (3128 bytes) is 0x1f.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Slice 3 data buffer (97 bytes) is 0x20.
00:00:10 - FFmpeg: [h264 @ 0x7f37e0019080] Decode to surface 0x14.
00:00:10 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:10 - Qt Info: Found "gamecontrollerdb.txt" at "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:10 - SDL Info (0): Loaded 175 new gamepad mappings
00:00:10 - Qt Info: Processing new PC at "192.168.10.103:47989" from mDNS with IPv6 address "<NULL>"
00:00:10 - Qt Info: Executing request: "http://192.168.10.103:47989/serverinfo?uniqueid=0123456789ABCDEF&uuid=a01e3b88be854bd38aa008a79409235d"
00:00:10 - Qt Info: Executing request: "https://192.168.10.103:47984/serverinfo?uniqueid=0123456789ABCDEF&uuid=97c982ad37aa43f2a7157faed9b175d6"
00:00:11 - SDL Info (0): Found host supported resolution: 1920x1080
00:00:11 - Qt Info: Executing request: "https://192.168.10.103:47984/launch?uniqueid=0123456789ABCDEF&uuid=7b6de62435034d669d1e14ed25d7fe4b&appid=1088017781&mode=1920x1080x60&additionalStates=1&sops=1&rikey=f69102ffecf766e9974d59b7466cb23d&rikeyid=-1764851110&localAudioPlayMode=0&surroundAudioInfo=196610&remoteControllersBitmap=1&gcmap=1"
00:00:16 - Qt Info: Launch response: "<?xml version=\"1.0\" encoding=\"UTF-16\"?><root protocol_version=\"0.1\" query=\"launch\" status_code=\"200\" status_message=\"OK\"><DisplayHeight>1080</DisplayHeight><DisplayWidth>1920</DisplayWidth><EnhancedStreamMode>1</EnhancedStreamMode><HdrMode>0</HdrMode><RefreshRate>60</RefreshRate><avkey>ok</avkey><gamesession>8acaf1a53dc47d66738f29845c1097bf</gamesession><rikey>ok</rikey><sessionUrl0>rtsp://192.168.10.103:48010</sessionUrl0><wssignaling>0</wssignaling></root>"
00:00:16 - Qt Info: Found matching interface: "wlan0" "E0:F8:47:07:C8:94" QFlags<QNetworkInterface::InterfaceFlag>(IsUp|IsRunning|CanBroadcast|CanMulticast)
00:00:16 - Qt Info: Interface Type: QNetworkInterface::Wifi
00:00:16 - Qt Info: Interface MTU: 1500
00:00:16 - SDL Info (0): RTSP port: 48010
00:00:16 - SDL Info (0): Initializing platform...
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Resolving host name...
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Initializing audio stream...
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Starting RTSP handshake...
00:00:16 - SDL Info (0): Audio port: 48000
00:00:16 - SDL Info (0): Video port: 47998
00:00:16 - SDL Info (0): Control port: 47999
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Initializing control stream...
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Initializing video stream...
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Initializing input stream...
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Starting control stream...
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Starting video stream...
00:00:16 - SDL Info (0): Video stream is 1920x1080x60 (format 0x1)
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Starting audio stream...
00:00:17 - SDL Info (0): Received first video packet after 0 ms
00:00:17 - SDL Info (0): Desired audio buffer: 240 samples (960 bytes)
00:00:17 - SDL Info (0): Obtained audio buffer: 240 samples (960 bytes)
00:00:17 - SDL Info (0): Audio stream has 2 channels
00:00:17 - SDL Info (0): done
00:00:17 - SDL Info (0): Starting input stream...
00:00:17 - SDL Info (0): Received first audio packet after 0 ms
00:00:17 - SDL Info (0): Initial audio resync period: 660 milliseconds
00:00:17 - SDL Info (0): done
00:00:17 - SDL Info (0): Qt UI screen is at (0,0)
00:00:17 - SDL Info (0): SDL found matching display 0
00:00:17 - SDL Info (0): Video decode unit queue overflow
00:00:17 - SDL Info (0): Waiting for IDR frame
00:00:17 - SDL Info (0): Waiting for IDR frame
00:00:17 - SDL Info (0): Waiting for IDR frame
00:00:17 - SDL Info (0): Waiting for IDR frame
00:00:17 - SDL Info (0): Waiting for IDR frame
00:00:17 - SDL Info (0): Waiting for IDR frame
00:00:17 - SDL Info (0): IDR frame request sent
Segmentation fault`

**Comment by J-o-h-n-s** [comment]
AppImage also launces, pairs, and connects with no problem.

My theory is that there are some dependencies missing, qould you perhaps add installing these to the docker script? the required ones for Debian are:

libegl1-mesa-dev libgl1-mesa-dev libopus-dev libqt5svg5-dev libsdl2-dev libsdl2-ttf-dev libssl-dev libavcodec-dev libva-dev libvdpau-dev libxkbcommon-dev qt5-default qt5-qmake qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev wayland-protocols qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-window2 qml-module-qtquick2

**Comment by veldenb** [comment]
They look like dependencies for compiling. Can you try running the appImage with ldd?
```
ldd ./Moonlight-3.2.0-x86_64.AppImage
```
It should dump a list with loaded libraries.

**Comment by bonswouar** [comment]
I'm having a Segfault too, although not when I start Moonlight but when I try to connect to a game _(a bit after "Starting RDSP handshake", I can't read the next message as it's too quick)_

Here is my log:
```log
00:00:20 - SDL Info (0): Audio stream has 2 channels
00:00:20 - SDL Info (0): done
00:00:20 - SDL Info (0): Starting input stream...
00:00:20 - SDL Info (0): done
00:00:20 - SDL Info (0): Received first audio packet after 0 ms
00:00:20 - SDL Info (0): Initial audio resync period: 915 milliseconds
00:00:20 - SDL Info (0): Qt UI screen is at (0,0)
00:00:20 - SDL Info (0): SDL found matching display 0
00:00:20 - SDL Info (0): Received first video packet after 0 ms
Segmentation fault
```

I've tried without success to run the `AppImage` (I didn't know libreelec could flawlessly run those?) :
```log
error: XDG_RUNTIME_DIR not set in the environment.
00:00:00 - SDL Info (0): Compiled with SDL 2.0.21
00:00:00 - SDL Info (0): Running with SDL 2.0.21
00:00:00 - Qt Info: Could not load the Qt platform plugin "xcb" in "" even though it was found.
00:00:00 - Qt Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted
```

And with debug on:
```log
error: XDG_RUNTIME_DIR not set in the environment.
00:00:00 - SDL Info (0): Compiled with SDL 2.0.21
00:00:00 - SDL Info (0): Running with SDL 2.0.21
00:00:00 - Qt Debug: QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms" ...
00:00:00 - Qt Debug: QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so"
00:00:00 - Qt Warning: Found metadata in lib /tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


00:00:00 - Qt Debug: Got keys from plugin meta data ("xcb")
00:00:00 - Qt Debug: QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_MoonlirSBlUQ/usr/bin/platforms" ...
00:00:00 - Qt Debug: Cannot load library /tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so: (libxcb.so.1: cannot open shared object file: No such file or directory)
00:00:00 - Qt Warning: QLibraryPrivate::loadPlugin failed on "/tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so: (libxcb.so.1: cannot open shared object file: No such file or directory)"
00:00:00 - Qt Info: Could not load the Qt platform plugin "xcb" in "" even though it was found.
00:00:00 - Qt Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted
```

And finally running `ldd` on this `AppImage` only returns this weird error:
```log
$	not a dynamic executable`
```

And I didn't try to build it from source but I believe there would be some libraries missing anyway?


P.S. I hope this is related to OP's problem, I can create a new issue if needed

**Comment by veldenb** [comment]
I tried the plugin on a Intel NUC today, same problem. Seems to be something with video decoding because the rest works fine. I guess some incompatibility. Will take some time to figure this out since the segmentation fault doesn't give a lot of information.

**Comment by J-o-h-n-s** [comment]
Sorry for late reply, also getting "not a dynamic executable" with ldd

**Comment by J-o-h-n-s** [comment]
> I'm having a Segfault too, on libreelect 10 generic x64, although not when I start Moonlight but when I try to connect to a game _(a bit after "Starting RDSP handshake", I can't read the next message as it's too quick)_
> 
> Here is my log:
> 
> ```
> 00:00:20 - SDL Info (0): Audio stream has 2 channels
> 00:00:20 - SDL Info (0): done
> 00:00:20 - SDL Info (0): Starting input stream...
> 00:00:20 - SDL Info (0): done
> 00:00:20 - SDL Info (0): Received first audio packet after 0 ms
> 00:00:20 - SDL Info (0): Initial audio resync period: 915 milliseconds
> 00:00:20 - SDL Info (0): Qt UI screen is at (0,0)
> 00:00:20 - SDL Info (0): SDL found matching display 0
> 00:00:20 - SDL Info (0): Received first video packet after 0 ms
> Segmentation fault
> ```
> 
> I've tried without success to run the `AppImage` (I didn't know libreelec could flawlessly run those?) :
> 
> ```
> error: XDG_RUNTIME_DIR not set in the environment.
> 00:00:00 - SDL Info (0): Compiled with SDL 2.0.21
> 00:00:00 - SDL Info (0): Running with SDL 2.0.21
> 00:00:00 - Qt Info: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> 00:00:00 - Qt Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: xcb.
> 
> Aborted
> ```
> 
> And with debug on:
> 
> ```
> error: XDG_RUNTIME_DIR not set in the environment.
> 00:00:00 - SDL Info (0): Compiled with SDL 2.0.21
> 00:00:00 - SDL Info (0): Running with SDL 2.0.21
> 00:00:00 - Qt Debug: QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms" ...
> 00:00:00 - Qt Debug: QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so"
> 00:00:00 - Qt Warning: Found metadata in lib /tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "xcb"
>         ]
>     },
>     "archreq": 0,
>     "className": "QXcbIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> 00:00:00 - Qt Debug: Got keys from plugin meta data ("xcb")
> 00:00:00 - Qt Debug: QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_MoonlirSBlUQ/usr/bin/platforms" ...
> 00:00:00 - Qt Debug: Cannot load library /tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so: (libxcb.so.1: cannot open shared object file: No such file or directory)
> 00:00:00 - Qt Warning: QLibraryPrivate::loadPlugin failed on "/tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_MoonlirSBlUQ/usr/plugins/platforms/libqxcb.so: (libxcb.so.1: cannot open shared object file: No such file or directory)"
> 00:00:00 - Qt Info: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> 00:00:00 - Qt Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: xcb.
> 
> Aborted
> ```
> 
> And finally running `ldd` on this `AppImage` only returns this weird error:
> 
> ```
> $	not a dynamic executable`
> ```
> 
> And I didn't try to build it from source but I believe there would be some libraries missing anyway?
> 
> P.S. I hope this is related to OP's problem, I can create a new issue if needed

This is the same issue as i'm having. Not when launching moonlight, but when connecting to a game

**Comment by veldenb** [comment]
I've updated the x86 installer. Can you try if this version works better: [plugin.program.moonlight-qt.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/8093197/plugin.program.moonlight-qt.zip) ?

I noticed a launch failed message from Kodi but moonlight did start on my NUC.

**Comment by veldenb** [comment]
Should be fixed in latest releases. Closing for now, feel free to re-open if necessary.

**Comment by bonswouar** [comment]
> Should be fixed in latest releases. Closing for now, feel free to re-open if necessary.

I've just installed the last release and I'm still having the segfaul just after "Received first video packet after 0 ms".
I wish there was more details in the logs..

If you need me to test something please don't hesitate

(I apparently can't reopen this issue)

**Comment by veldenb** [comment]
@bonswouar have you tried updating moonlight using the configuration menu? The plugin needs to create a new moonlight build before the fix becomes effective.

**Comment by bonswouar** [comment]
@veldenb Oh that makes sense, sorry, it totally works now that I've updated the docker container, thanks!

**Comment by veldenb** [comment]
@bonswouar you mean this?

"Gamepad shortcuts:
Start (press and hold) - Toggle mouse mode" ?

It's already in Moonlight :)

**Comment by bonswouar** [comment]
@veldenb Woh they thought of everything, amazing! :)
I haven't used Moonlight much yet, gonna leave this here just in case somebody is looking for gamepad controls: https://wiki.batocera.org/systems:moonlight#moonlight_shortcuts

*Now I have to stop spamming this issue ;)*
